/**
 * Component-specific tokens — Tac UI brand.
 * Increased padding for airy feel, softer radii.
 */
export const component = {
  button: {
    sm: { height: 34, paddingX: 18, paddingY: 8, fontSize: 12, borderRadius: 8, iconSize: 16 },
    md: { height: 42, paddingX: 28, paddingY: 12, fontSize: 13, borderRadius: 10, iconSize: 18 },
    lg: { height: 50, paddingX: 36, paddingY: 16, fontSize: 15, borderRadius: 14, iconSize: 20 },
  },
  input: {
    height: 42,
    paddingX: 18,
    paddingY: 12,
    fontSize: 14,
    borderRadius: 10,
    iconSize: 18,
    iconPadding: 42,
  },
  card: {
    padding: 28,
    gap: 20,
    borderRadius: 16,
    titleSize: 17,
    bodySize: 14,
  },
  badge: {
    paddingX: 12,
    paddingY: 6,
    fontSize: 12,
    fontWeight: 500,
    borderRadius: 9999,
  },
  checkbox: {
    wrapperPaddingX: 16,
    wrapperPaddingY: 10,
    wrapperRadius: 10,
    gap: 12,
    size: 20,
    borderRadius: 6,
    borderWidth: 2,
    iconSize: 14,
    labelSize: 14,
  },
  radio: {
    wrapperPaddingX: 16,
    wrapperPaddingY: 10,
    wrapperRadius: 10,
    gap: 12,
    size: 20,
    borderWidth: 2,
    checkedBorderWidth: 6,
    labelSize: 14,
  },
  switch: {
    width: 52,
    height: 32,
    thumbSize: 24,
    thumbOffset: 4,
    thumbTranslateOn: 24,
    thumbTranslateOff: 4,
  },
  chip: {
    paddingX: 16,
    paddingY: 8,
    fontSize: 13,
    borderRadius: 9999,
    iconSize: 14,
    iconPaddingX: 12,
  },
  tabs: {
    primary: {
      paddingX: 20,
      paddingY: 12,
      fontSize: 14,
      indicatorHeight: 2,
    },
    secondary: {
      paddingX: 20,
      paddingY: 8,
      fontSize: 13,
      containerPadding: 4,
      containerRadius: 14,
      itemRadius: 10,
    },
  },
  slider: {
    trackHeight: 6,
    thumbSize: 20,
    thumbBorderWidth: 2,
  },
  tooltip: {
    simple: { paddingX: 14, paddingY: 8, fontSize: 13, borderRadius: 10 },
    rich: { paddingX: 16, paddingY: 10, maxWidth: 240, borderRadius: 10 },
    delay: 150,
  },
  avatar: {
    sm: { size: 28, fontSize: 11 },
    md: { size: 36, fontSize: 14 },
    lg: { size: 48, fontSize: 18 },
    xl: { size: 64, fontSize: 24 },
    statusDot: 10,
    statusBorder: 2,
  },
  divider: {
    thickness: 1,
    thickThickness: 8,
    insetMargin: 64,
    labelSize: 12,
  },
  progress: {
    linear: { height: 8, borderRadius: 9999 },
    circular: { strokeWidth: 4, textSize: 14 },
  },
  snackbar: {
    paddingTop: 16,
    paddingRight: 18,
    paddingBottom: 16,
    paddingLeft: 22,
    borderRadius: 14,
    gap: 12,
    iconSize: 18,
    messageSize: 14,
    actionPaddingX: 14,
    actionPaddingY: 6,
    actionRadius: 8,
    actionSize: 13,
  },
  dialog: {
    width: 380,
    borderRadius: 20,
    headerPaddingX: 28,
    headerPaddingY: 24,
    footerPaddingX: 28,
    footerPaddingY: 20,
    titleSize: 17,
    descSize: 14,
    footerGap: 14,
  },
  animatedToggle: {
    size: 40,
    borderRadius: 10,
    iconSize: 20,
  },
} as const;
