/**
 * Component-specific tokens — Tac UI brand.
 * Increased padding for airy feel, harmonious radii.
 */
export const component = {
  button: {
    sm: { height: 32, paddingX: 16, paddingY: 6, fontSize: 13, borderRadius: 8, iconSize: 16 },
    md: { height: 44, paddingX: 20, paddingY: 10, fontSize: 15, borderRadius: 12, iconSize: 18 },
    lg: { height: 50, paddingX: 28, paddingY: 14, fontSize: 17, borderRadius: 14, iconSize: 20 },
  },
  input: {
    sm: { height: 32, paddingX: 12, fontSize: 13, borderRadius: 8, iconSize: 16, iconPadding: 34 },
    md: { height: 44, paddingX: 16, fontSize: 15, borderRadius: 12, iconSize: 18, iconPadding: 42 },
    lg: { height: 50, paddingX: 20, fontSize: 17, borderRadius: 14, iconSize: 20, iconPadding: 46 },
  },
  card: {
    padding: 24,
    gap: 16,
    borderRadius: 16,
    titleSize: 17,
    bodySize: 15,
  },
  badge: {
    paddingX: 12,
    paddingY: 6,
    fontSize: 12,
    fontWeight: 500,
    borderRadius: 9999,
  },
  checkbox: {
    wrapperPaddingX: 16,
    wrapperPaddingY: 10,
    wrapperRadius: 10,
    gap: 12,
    size: 22,
    borderRadius: 6,
    borderWidth: 1.5,
    iconSize: 14,
    labelSize: 15,
  },
  radio: {
    wrapperPaddingX: 16,
    wrapperPaddingY: 10,
    wrapperRadius: 10,
    gap: 12,
    size: 22,
    borderWidth: 1.5,
    checkedBorderWidth: 6,
    labelSize: 15,
  },
  switch: {
    width: 51,
    height: 31,
    thumbSize: 27,
    thumbOffset: 2,
    thumbTranslateOn: 22,
    thumbTranslateOff: 2,
  },
  chip: {
    paddingX: 16,
    paddingY: 8,
    fontSize: 13,
    borderRadius: 9999,
    iconSize: 14,
    iconPaddingX: 12,
  },
  tabs: {
    primary: {
      paddingX: 20,
      paddingY: 12,
      fontSize: 14,
      indicatorHeight: 2,
    },
    secondary: {
      paddingX: 20,
      paddingY: 8,
      fontSize: 13,
      containerPadding: 4,
      containerRadius: 10,
      itemRadius: 8,
    },
  },
  slider: {
    trackHeight: 4,
    thumbSize: 28,
    thumbBorderWidth: 0,
  },
  tooltip: {
    simple: { paddingX: 14, paddingY: 8, fontSize: 13, borderRadius: 10 },
    rich: { paddingX: 16, paddingY: 10, maxWidth: 240, borderRadius: 10 },
    delay: 150,
  },
  avatar: {
    sm: { size: 28, fontSize: 11 },
    md: { size: 36, fontSize: 14 },
    lg: { size: 48, fontSize: 18 },
    xl: { size: 64, fontSize: 24 },
    statusDot: 10,
    statusBorder: 2,
  },
  divider: {
    thickness: 1,
    thickThickness: 1,
    insetMargin: 64,
    labelSize: 12,
  },
  progress: {
    linear: { height: 6, borderRadius: 9999 },
    circular: { strokeWidth: 4, textSize: 14 },
  },
  snackbar: {
    paddingTop: 16,
    paddingRight: 18,
    paddingBottom: 16,
    paddingLeft: 22,
    borderRadius: 12,
    gap: 12,
    iconSize: 18,
    messageSize: 14,
    actionPaddingX: 14,
    actionPaddingY: 6,
    actionRadius: 8,
    actionSize: 13,
  },
  dialog: {
    width: 320,
    borderRadius: 14,
    headerPaddingX: 24,
    headerPaddingY: 20,
    footerPaddingX: 24,
    footerPaddingY: 20,
    titleSize: 17,
    descSize: 13,
    footerGap: 8,
  },
  animatedToggle: {
    size: 40,
    borderRadius: 10,
    iconSize: 20,
  },
} as const;
